name: Run Spectral on Pull Requests

on:
  pull_request:
    branches: [ main ]
    paths:
      - "openapi.yaml"
  push:
    branches: [ main ]
    paths:
      - "openapi.yaml"

permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  spectral-lint:
    name: Run Spectral
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: stoplightio/spectral-action@latest
        with:
          file_glob: "openapi.yaml"
          spectral_ruleset: ".spectral.yaml"
          args: "-F warn"   
